## Vectors in linear algebra : 

vectors is a set of elements with the same nature, let $\mathbb{V}_n$ a set of vectors with dimenssion $n$ , for example $v \in \mathbb{V_{3}}$ so $dim({v}) = 3$ .  
* $v = (1, 2, 3)$ it's a vecotor of 3 elements, for example if we consider the vector is a plan, we can say that $v = (x, y, z) = (axe_x, axe_y, axe_z)$ .

In [1]:
# Create a vector in python : 
import numpy as np

In [11]:
v1 = np.array([
    1,
    2,
    3
])

In [12]:
v1

array([1, 2, 3])

In [13]:
print("The dim of V1 : ", v1.size)

The dim of V1 :  3


## Operations in vectors : 

let $(v_1, v_2) \in \mathbb{V_n} \times \mathbb{V_n}$, so *dim*($v_1$) $ =n$ and *dim*($v_2$) $ =n$ and $v_1 = (a_1, a_2, ..., a_n)$ and $v_2 = (b_1, b_2, ..., b_m)$ .

$v_1 + v_2 = (a_1 + b_1, a_2 + b_2, ..., a_n + b_n)$ . 

In [19]:
# Example : 
v1 = np.array([1, 2, 3])
v2 = np.array([1, 2, 3])

v1 + v2

array([2, 4, 6])

let $v \in \mathbb{V_n}$, $\forall \alpha \in \mathbb{R} $ and $ v = (a_1, a_2, ..., a_n)$ .

$\alpha \times v = (\alpha . a_1, \alpha . a_2, ..., \alpha . a_n)$


In [25]:
# ExampleV1 : 
v1 = np.array([1, 3, 6])
2 * v1

array([ 2,  6, 12])