In [15]:
import torch

In [16]:
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

In [17]:
def forward(x):
    y = w * x + b
    return y

In [18]:
x = torch.tensor([
    [1],
    [2]
])
x

tensor([[1],
        [2]])

In [19]:
yhat = forward(x)

In [20]:
yhat

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

We can use a class linear in pytorch to make a regression : 

In [21]:
from torch.nn import Linear

In [25]:
torch.manual_seed(1) # In order to get the ame results evrytime we run our code

In [24]:
# Creting a model object : 
model = Linear(in_features=1, out_features=1)

In [32]:
# Desiplay the params of our model : 
list(model.parameters())

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [34]:
x = torch.tensor(
    [0.0]
)

In [35]:
yhat = model(x)

In [36]:
yhat

tensor([-0.4414], grad_fn=<AddBackward0>)

In [38]:
# Or 2D : 
x2 = torch.tensor([
    [1.0],
    [0.0]
])

yhat = model(x2)

In [39]:
yhat

tensor([[ 0.0739],
        [-0.4414]], grad_fn=<AddmmBackward0>)

Create a custom regression custom model class 

In [41]:
import torch.nn as nn

class LR(nn.Module):
    def __init__(self, in_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(in_size, output_size)
        
    def forward(self, x):
        out = self.linear(x)
        return out