In [1]:
import torch.nn as nn

In [2]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        out = self.linear(x)
        return out

In [4]:
from torch.nn import Linear
import torch

In [5]:
torch.manual_seed(1)

model = LR(input_size=2, output_size=2)

list(model.parameters())

[Parameter containing:
 tensor([[ 0.3643, -0.3121],
         [-0.1371,  0.3319]], requires_grad=True),
 Parameter containing:
 tensor([-0.6657,  0.4241], requires_grad=True)]

In [6]:
x = torch.tensor([[1.0, 2.0]])
yhat = model(x)

In [7]:
yhat

tensor([[-0.9256,  0.9508]], grad_fn=<AddmmBackward0>)