In [24]:
import torch.nn as nn
from torch import optim

In [25]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        out = self.linear(x)
        return out

In [26]:
from torch.nn import Linear
import torch

In [27]:
torch.manual_seed(1)

model = LR(input_size=2, output_size=2)

list(model.parameters())

[Parameter containing:
 tensor([[ 0.3643, -0.3121],
         [-0.1371,  0.3319]], requires_grad=True),
 Parameter containing:
 tensor([-0.6657,  0.4241], requires_grad=True)]

In [28]:
x = torch.tensor([
    [80.3, 85.3]
])
yhat = model(x)

In [29]:
yhat

tensor([[ 1.9690, 17.7270]], grad_fn=<AddmmBackward0>)

Training

In [30]:
from torch.utils.data import Dataset, DataLoader

class data2D(DataLoader):
    def __init__(self):
        self.x = torch.zeros(20, 2)
        self.x[:, 0] = torch.arange(-1, 1, 0.1)
        self.x[:, 1] = torch.arange(-1, 1, 0.1)
        self.w = torch.tensor([[1.0], [1.0]])
        self.b = 1
        self.f = torch.mm(self.x, self.w) + self.b
        self.y = self.f + 0.1*torch.randn((self.x.shape[0], 1))
        self.len = self.x.shape[0]
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        return self.len

In [31]:
# Creating a data set object 

data_set = data2D()
criterion = nn.MSELoss()
trainloader = DataLoader(dataset=data_set, batch_size=1)

optimizer = optim.SGD(model.parameters(), lr=0.1)

model = LR(input_size=2, output_size=2)

In [32]:
for epoch in range(100):
    for x, y in trainloader:

        yhat = model(x)
        loss = criterion(yhat, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

c:\Users\khaba\anaconda3\Lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1, 1])) that is different to the input size (torch.Size([1, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [33]:
x = torch.tensor([
    [80.3, 85.3]
])

# Making predictions : 

model(x)

tensor([[42.9201,  1.2983]], grad_fn=<AddmmBackward0>)