In [2]:
from torch.nn import Linear
import torch

In [3]:
torch.manual_seed(1)    # To gte the same result every time we run the code

In [4]:
model = Linear(in_features=2, out_features=2)   # in features is the numbers of colomns of X ( so we have x1 and x2)

In [5]:
# Creating ana input : 
X = torch.tensor([
    [1.0, 3.0]
])

yhat = model(X)
yhat

tensor([[-1.2377,  1.2827]], grad_fn=<AddmmBackward0>)

In [6]:
# custom model 

import torch.nn as nn
from torch import nn, optim

class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

In [9]:
from torch.utils.data import Dataset, DataLoader

class data2D(DataLoader):
    def __init__(self):
        self.x = torch.zeros(20, 2)
        self.x[:, 0] = torch.arange(-1, 1, 0.1)
        self.x[:, 1] = torch.arange(-1, 1, 0.1)
        self.w = torch.tensor([[1.0], [1.0]])
        self.b = 1
        self.f = torch.mm(self.x, self.w) + self.b
        self.y = self.f + 0.1*torch.randn((self.x.shape[0], 1))
        self.len = self.x.shape[0]
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        return self.len

In [16]:
data_set = data2D()
data_set.__getitem__(8)

(tensor([-0.2000, -0.2000]), tensor([0.6145]))

In [8]:
criterion = nn.MSELoss()
train_loader = DataLoader(dataset=data_set, batch_size=2)
model = LR(input_size=2, output_size=1)

In [8]:
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [9]:
for epoch in range(100):
    for x, y in train_loader:
        yhat = model(x)
        loss = criterion(yhat, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

In [10]:
test = torch.tensor([-52.0 , 10.0])
model(test)

tensor([-58.2005], grad_fn=<ViewBackward0>)